Repository UBCSailbot/docs, pull requests merged in 2022-09, with the labels that each got.

#38 GitHub Workflow Documentation
  .gitignore
  .markdown-link-check.json
  .vscode/cspell.json
  .vscode/settings.json
  docs/assets/images/github/workflow/branch_comparison.png
  docs/assets/images/github/workflow/create_pr.png
  docs/assets/images/github/workflow/gh_assignee.png
  docs/assets/images/github/workflow/gh_labels.png
  docs/assets/images/github/workflow/gh_milestone.png
  docs/assets/images/github/workflow/gh_project.png
  docs/assets/images/github/workflow/issue_list.png
  docs/assets/images/github/workflow/issue_tab.png
  docs/assets/images/github/workflow/issue_template_list.png
  docs/assets/images/github/workflow/merge_conflict.png
  docs/assets/images/github/workflow/merge_conflict_file.png
  docs/assets/images/github/workflow/new_feature_template.png
  docs/assets/images/github/workflow/pr_comment_snippet.png
  docs/assets/images/github/workflow/pr_example.png
  docs/assets/images/github/workflow/pr_merge.png
  docs/reference/github/workflow/branches.md
  docs/reference/github/workflow/index.md
  docs/reference/github/workflow/issues.md
  docs/reference/github/workflow/pr.md
  mkdocs.yml
Labels: documentation, new-page

#49 Ignore line length of tables and add workspace color
  .markdownlint.json
  .vscode/extensions.json
  .vscode/settings.json
Labels: infrastructure

#52 Fix scheduled tasks CI
  .github/workflows/scheduled_tasks.yml
Labels: bug, infrastructure

#39 Python reference pages
  .vscode/cspell.json
  docs/reference/python/conventions.md
  docs/reference/python/index.md
  docs/reference/python/virtual-environments.md
  mkdocs.yml
Labels: documentation, new-page

#54 Update vscode configuration
  .vscode/extensions.json
  .vscode/launch.json
Labels: infrastructure, ignore-for-release

#50 Create ROS reference page
  .vscode/cspell.json
  docs/reference/ros.md
  mkdocs.yml
Labels: documentation, new-page

#55 Link to internal documentation for Python virtual environments
  README.md
  docs/reference/ros.md
Labels: documentation, ignore-for-release
