Repository UBCSailbot/docs, pull requests merged in 2022-11, with the labels that each got.

#89 Create CODEOWNERS
  .github/CODEOWNERS
Labels: infrastructure

#87 Update Pull Request Page
  docs/assets/images/github/workflow/branch_comparison.png
  docs/assets/images/github/workflow/create_pr.png
  docs/assets/images/github/workflow/pr_example.png
  docs/reference/github/workflow/branches.md
Labels: documentation, update-page

#90 Fix typo
  docs/reference/ros.md
Labels: documentation, ignore-for-release

#92 Update README.md
  README.md
Labels: documentation, maintenance

#86 GitHub Action for Linting Hyperlink Redirection
  .github/actions/lint/action.yml
  .github/actions/lint/lint_links.py
  .github/workflows/lint.yml
  docs/reference/cpp/differences.md
  docs/reference/cpp/index.md
  docs/reference/cpp/tools.md
  docs/reference/github/workflow/branches.md
  docs/reference/github/workflow/index.md
  docs/reference/github/workflow/issues.md
  docs/reference/github/workflow/pr.md
  docs/reference/markdown.md
  docs/reference/python/conventions.md
  docs/reference/python/index.md
  docs/reference/python/virtual-environments.md
  docs/reference/ros.md
Labels: enhancement, infrastructure

#95 Remove Patrick as codeowner
  .github/CODEOWNERS
Labels: infrastructure, ignore-for-release

#93 Create docs page for workspace setup
  .markdown-link-check.json
  .vscode/cspell.json
  docs/current/index.md
  docs/current/sailbot_workspace/overview.md
  docs/current/sailbot_workspace/run.md
  docs/current/sailbot_workspace/setup.md
  mkdocs.yml
Labels: documentation, new-page

#98 Point to setup instructions on the site
  docs/reference/ros.md
Labels: infrastructure, ignore-for-release

#105 Add Linkedin icon on bottom banner
  mkdocs.yml
Labels: enhancement, maintenance, update-page
