Repository UBCSailbot/docs, pull requests merged in 2022-10, with the labels that each got.

#57 Proofread ROS page
  docs/reference/ros.md
Labels: documentation, update-page, ignore-for-release

#58 Clarify instruction
  docs/reference/ros.md
Labels: documentation, ignore-for-release

#59 Change url from remote to local
  README.md
Labels: infrastructure, ignore-for-release

#60 Revert "Change url from remote to local"
  README.md
Labels: infrastructure, ignore-for-release

#65 Dropdown pages to separate pages
  mkdocs.yml
Labels: documentation, enhancement

#66 Ignore bots in autogenerated release notes and add edit button to each page
  .github/release.yml
  mkdocs.yml
Labels: infrastructure

#63 C++ Reference Pages
  .vscode/cspell.json
  docs/reference/cpp/differences.md
  docs/reference/cpp/index.md
  docs/reference/cpp/tools.md
  mkdocs.yml
Labels: documentation, new-page

#68 Add Update Dependencies section in main README
  README.md
Labels: infrastructure, ignore-for-release

#71 Update file edit icon and hide sub-pages by default
  mkdocs.yml
Labels: infrastructure

#67 Markdown Reference Page
  .markdown-link-check.json
  docs/assets/images/markdown/issue_md_rendered.png
  docs/assets/images/markdown/issue_md_text.png
  docs/reference/markdown.md
  mkdocs.yml
Labels: documentation, new-page

#53 Sailing knowledge
  docs/assets/images/sailing/bear_off.jpg
  docs/assets/images/sailing/bear_off_then_gybe.jpg
  docs/assets/images/sailing/bearing_vs_heading.jpg
  docs/assets/images/sailing/gybe.jpg
  docs/assets/images/sailing/head_up.jpg
  docs/assets/images/sailing/parts_of_boat.jpg
  docs/assets/images/sailing/points_of_sail.jpg
  docs/assets/images/sailing/regions_of_hull.jpg
  docs/assets/images/sailing/tack.jpg
  docs/assets/images/sailing/tack_other_meaning.jpg
  docs/assets/images/sailing/track_made_good.jpg
  docs/assets/images/sailing/types_of_turn.jpg
  docs/assets/images/sailing/upwind_downwind_sailing.jpg
  docs/assets/images/sailing/wind_types.jpg
  docs/javascripts/mathjax.js
  docs/reference/sailing/boat_parts.md
  docs/reference/sailing/index.md
  docs/reference/sailing/miscellaneous.md
  docs/reference/sailing/points_of_sail.md
  docs/reference/sailing/turning.md
  mkdocs.yml
Labels: documentation, new-page

#73 Revamp CI
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/weekly-lint.yml
  README.md
Labels: infrastructure

#75 Add Publish status badge
  README.md
Labels: infrastructure, ignore-for-release

#80 Update VS Code extensions
  .vscode/extensions.json
  .vscode/settings.json
Labels: infrastructure

#84 Update VS Code command name
  docs/reference/ros.md
Labels: documentation

#83 Added turning flowchart; wind direction conventions
  docs/reference/sailing/miscellaneous.md
  docs/reference/sailing/turning.md
  mkdocs.yml
Labels: documentation, update-page
