Repository UBCSailbot/docs, pull requests merged in 2023-06, with the labels that each got.

#141 Update social card color
  mkdocs.yml
Labels: infrastructure

#142 Use CI in sailbot workspace
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/weekly-lint.yml
Labels: infrastructure

#143 Fix Tests CI badge
  README.md
Labels: bug, infrastructure

#144 Add versioning to site
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  .gitignore
  docs/overrides/main.html
  docs/requirements.txt
  mkdocs.yml
Labels: infrastructure

#146 Deploy docs to main on workflow dispatch
  .github/workflows/tests.yml
Labels: bug, infrastructure

#145 Sailbot Workspace v1.2.0 Updates
  README.md
  docs/current/boat_simulator/overview.md
  docs/current/custom_interfaces/overview.md
  docs/current/local_pathfinding/overview.md
  docs/current/network_systems/overview.md
  docs/current/sailbot_workspace/docker_images.md
  docs/current/sailbot_workspace/how_to.md
  docs/current/sailbot_workspace/run.md
  docs/current/sailbot_workspace/setup.md
  docs/current/sailbot_workspace/workflow.md
  docs/current/website/overview.md
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation

#152 Fix light theme table of contents color scheme
  docs/javascripts/table_of_contents_themes.js
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: bug
