Repository UBCSailbot/docs, pull requests merged in 2023-01, with the labels that each got.

#116 Correct conda default python version
  docs/reference/python/virtual-environments.md
Labels: documentation, update-page, ignore-for-release

#114 Render only trailing whitespace
  .vscode/settings.json
Labels: infrastructure, ignore-for-release

#109 Update Python Conventions Page with Python Hinting
  .vscode/cspell.json
  docs/reference/python/conventions.md
  docs/reference/python/index.md
  docs/reference/python/virtual-environments.md
Labels: documentation, update-page

#118 Update social card theme
  mkdocs.yml
Labels: documentation, enhancement

#119 Fix bug in mkdocs config file
  mkdocs.yml
Labels: bug, ignore-for-release

#120 Enable dependabot
  .github/dependabot.yml
Labels: infrastructure
