Repository UBCSailbot/docs, pull requests merged in 2023-10, with the labels that each got.

#169 Add documentation for new repositories
  docs/current/controller/overview.md
  docs/current/notebooks/overview.md
  mkdocs.yml
Labels: documentation, new-page

#170 Add current project name
  docs/current/overview.md
  docs/current/sailbot_workspace/setup.md
  docs/current/sailbot_workspace/workflow.md
  docs/reference/ros.md
Labels: documentation, update-page

#171 Added Section Under Docker Desktop On Setup Page To Address Docker Starting Error
  docs/assets/images/sailbot_workspace/workflow/sailbot_bug.png
  docs/current/sailbot_workspace/setup.md
Labels: update-page
