Repository UBCSailbot/docs, pull requests merged in 2023-09, with the labels that each got.

#161 Add how to open sailbot workspace
  .markdownlint.json
  docs/current/sailbot_workspace/workflow.md
Labels: documentation, update-page

#163 Expand all navigation tabs by default
  mkdocs.yml
Labels: enhancement

#167 Stop cancelling in progress jobs
  .github/workflows/tests.yml
Labels: bug, infrastructure
