Repository UBCSailbot/docs, pull requests merged in 2024-02, with the labels that each got.

#200 Update pre-base image definition location
  docs/current/sailbot_workspace/docker_images.md
Labels: infrastructure

#202 Add ROS parameters page to docs site
  docs/current/sailbot_workspace/parameters.md
  mkdocs.yml
Labels: documentation

#201 Document how to add runtime Python and Apt dependencies to ROS packages
  docs/current/sailbot_workspace/how_to.md
Labels: documentation, infrastructure

#203 Update how to mange software packages
  docs/current/sailbot_workspace/how_to.md
Labels: documentation, update-page
